### ISSUE TITLE
Arbeitsaufteilung/Konzept für die Programmierung definieren.

### ISSUE THREAD

**Issue by Zuhlek** [SandroGuerotto/PrettySecureCloud#15]

**Comment by SandroGuerotto** [comment]
### Tasks
Login:
- Screen FXML mit Controller
- Login und Registrierung(Was für eine Verschlüsselung)

Anbindung an Dienste:
- Dropbox via SDK
- Filesystem via User definierter Pfad

FileBrowser:
- Dateibaum aufbauen
- Screen FXML mit Controller
- DragDrop Event registrieren
- Up/Download registrieren
- Verarbeitungsfortschritt

"Backend":
- Verschlüsselung (async)
- Up/Download (async)
- Persistenz: PSC Login, Login von Cloud / Pfade, Key
- Idee: alles in ein File und dieses dann als Export / Import zur Verfügung stellen
